### PR TITLE
Update met  config before ICHEP

### PR DESCRIPTION
**Pull request by mariadalfonso**
1) added the badMuon and badchargedhadron filters in the susyCore and metSequence;
2) improved cmgListChunksToResub
3) update sample files and xsection
4) METtree: added significance; metUnclustered uncertainties; update GT for pre-processing

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@gpetruc updated the cmgListChunksToResub as discussed

**Comment by bachtis** [comment]
HI can we have the MET filter analyzers somewhere common ?It is easier to find them rather than have them hidden in TTHAnalysis

**Comment by gpetruc** [comment]
Fine for me.
In ObjectStudies?

Giovanni

On Tue, Jun 28, 2016 at 11:25 AM, Michalis Bachtis <notifications@github.com

**Comment by bachtis** [comment]
Maybe root tools?

---- Giovanni Petrucciani wrote ----

Fine for me.
In ObjectStudies?

Giovanni

On Tue, Jun 28, 2016 at 11:25 AM, Michalis Bachtis <notifications@github.com

**Pull request merged**
