### PR TITLE
Major set of post-Moriond multilepton updates (80X)

### PR DESCRIPTION
**Pull request by peruzzim**
As #45 + updates to cfg and samples files for 2016. Needs CERN-PH-CMG/cmg-cmssw#647.

Includes merging of cmgtools-lite/76X into 80X.

### CODE REVIEW

**Comment by gpetruc** [comment]
Anybody from other susy modes (esp. hadronic) can test that this PR does not interfer with their workflow and comment here when done?
Given the size of the PR, I'd like to merge it soon, but a test of something besides multilepton would be good to have.
Thanks,
Giovanni

**Comment by mmasciov** [comment]
@pandolf @mangano 
We will try to test it soon

**Comment by mmasciov** [comment]
@gpetruc @mangano 
This PR looks okay for MT2 ( I assume validation to be valid also for PR #45 )

**Comment by gpetruc** [comment]
Thanks!

**Pull request merged**
