### PR TITLE
Bad PF muon filter and duplicate filter for Moriond 2017

### PR DESCRIPTION
**Pull request by schoef**
Based on https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2786.html

- did a sanity test on couple hundred events and filter decision seems to be correct. Did not check on bad events since I have only the AOD of those.
- store the bad and duplicate muons in event

Needs further testing on bad events.

### CODE REVIEW

**Comment by gpetruc** [comment]
It would be good to also save in the tree in addition to the bools the max pt of any clone muon and of any bad-but-not-clone muon. e.g. as below (but to be tested!)
```
NTupleVariable("badCloneMuonMoriond2017_maxPt",  lambda ev: max(mu.pt() for mu in ev.badCloneMuonMoriond2017_badMuons) if ev.badCloneMuonMoriond2017 else 0, help="max pt of any clone muon found in event (Moriond 2017 filter)"),
NTupleVariable("badNotCloneMuonMoriond2017_maxPt",  lambda ev: max((mu.pt() if mu not in ev.badCloneMuonMoriond2017_badMuons else 0) for mu in ev.badMuonMoriond2017_badMuons) if ev.badMuonMoriond2017 else 0, help="max pt of any non-clone muon found in event (Moriond 2017 filter)"),
```

**Comment by schoef** [comment]
@gpetruc added, and corrected an obvious mistake in the logic.
Let's wait with the merge until we've frozen the selection for the reminiaod.

**Comment by gpetruc** [comment]
Hi Robert,
Can you update the filter to the version that went in 8_0_26 so that we can merge this PR?
Thanks
Giovanni

**Comment by schoef** [comment]
@gpetruc Done.

**Pull request merged**
